// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Custom namespace for serial port because
// the .d.ts file does not allow regular "import" statements
declare namespace SerialPort {
    interface PortInfo {
        path: string;
        manufacturer: string | undefined;
        serialNumber: string | undefined;
        pnpId: string | undefined;
        locationId: string | undefined;
        productId: string | undefined;
        vendorId: string | undefined;
    }
  }

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface SerialContext {
    listPorts: () => Promise<SerialPort.PortInfo[]>;
    openPort: (portPath: string) => Promise<boolean>;
    closePort: () => boolean;
    sendCommand: (jsonCommand: string) => void;
    onStatus: (callback: (jsonStatus: string) => void) => void;
}

interface CameraContext {
    savePicture: (imgEncoded: string) => Promise<void>;
}

declare interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    camera: CameraContext;
    serial: SerialContext;
}
