// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

import { CameraHwControl } from "./types/camera";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Database types (also exported from src/types/database.ts for component usage)
interface SpeedViolation {
  id: number;
  timestamp: string; // ISO 8601 format
  measuredSpeed: number;
  maxSpeed: number;
  imagePath: string;
  createdAt: string; // ISO 8601 format
}

interface CreateSpeedViolation {
  measuredSpeed: number;
  maxSpeed: number;
  imagePath: string;
}



// Custom namespace for serial port because
// the .d.ts file does not allow regular "import" statements
declare namespace SerialPort {
    interface PortInfo {
        path: string;
        manufacturer: string | undefined;
        serialNumber: string | undefined;
        pnpId: string | undefined;
        locationId: string | undefined;
        productId: string | undefined;
        vendorId: string | undefined;
    }
  }

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface SerialContext {
    listPorts: () => Promise<SerialPort.PortInfo[]>;
    openPort: (portPath: string) => Promise<boolean>;
    closePort: () => boolean;
    sendCommand: (jsonCommand: string) => void;
    onStatus: (callback: (jsonStatus: string) => void) => void;
    offStatus: (callback: (jsonStatus: string) => void) => void;
}

interface CameraContext {
    savePicture: (imgEncoded: string) => Promise<string>;
    getImageData: (imagePath: string) => Promise<string | null>;
    getAvailableCameras: () => Promise<{ id: number; name: string }[]>;
    getAvailableHwControls: (cameraId: number) => Promise<CameraHwControl[]>;
    setHwControl: (cameraId: number, controlName: string, value: number) => Promise<void>;
    getHwControl: (cameraId: number, controlName: string) => Promise<number>;
}

interface DatabaseContext {
    addViolation: (violation: CreateSpeedViolation) => Promise<SpeedViolation>;
    getViolations: (limit?: number, offset?: number) => Promise<SpeedViolation[]>;
    getViolationById: (id: number) => Promise<SpeedViolation | undefined>;
    getViolationsByDateRange: (startDate: string, endDate: string) => Promise<SpeedViolation[]>;
    deleteViolation: (id: number) => Promise<boolean>;
    getViolationCount: () => Promise<number>;
}

declare interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    camera: CameraContext;
    serial: SerialContext;
    database: DatabaseContext;
}
